// src/screens/Legal.jsx
// About, Terms, Privacy, Cookies, Cookie Preferences, Disclaimer.
// Auto-populated for Littgram (personal project, India).

import { useParams, Link } from 'react-router-dom';
import { useState } from 'react';

const UPDATED = 'July 2026';
const CONTACT = 'contact-us@littgram.com';

const S = ({ title, children }) => (
  <div style={{ marginBottom: 18 }}>
    <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 6 }}>{title}</div>
    <div className="sub" style={{ lineHeight: 1.65 }}>{children}</div>
  </div>
);

function About() {
  return (
    <>
      <S title="What is Littgram?">
        Littgram is a literary social space for Indian-language literature. Read classics in
        Bengali, Hindi, Marathi and English; listen to books and five-minute audio summaries;
        share the lines that move you; and keep a reading streak with monthly challenges.
      </S>
      <S title="What we believe">
        The great books of Bengal, the Hindi heartland and Maharashtra deserve the same beautiful,
        modern reading experience as anything in English. Littgram digitizes public-domain works,
        preserves their original scripts faithfully, and pairs them with English editions so the
        stories travel further.
      </S>
      <S title="The stack, briefly">
        Books are digitized from scans using AI OCR, translated with AI assistance, and narrated
        with Indian-language text-to-speech voices. Littgram is an independent personal project,
        built and run from India.
      </S>
      <S title="Reach us">
        Questions, corrections, takedown requests or book suggestions: <b>{CONTACT}</b>
      </S>
    </>
  );
}

function Terms() {
  return (
    <>
      <S title="1. Acceptance">
        By using Littgram you agree to these terms. Littgram is a personal, non-commercial
        project provided as-is, without warranties of any kind.
      </S>
      <S title="2. Your account">
        Sign-in uses your Google account. You are responsible for activity under your account.
        Handles and posts must not impersonate others or contain unlawful content.
      </S>
      <S title="3. Your content">
        Quotes, captions and posts you publish are visible to all Littgram users. You retain
        ownership of what you write and grant Littgram a licence to display it within the app.
        We may remove content that is abusive, unlawful or off-topic.
      </S>
      <S title="4. Books and copyright">
        Littgram hosts works we believe to be in the public domain in India, plus AI-generated
        translations and summaries of those works. If you believe any content infringes your
        rights, write to {CONTACT} and we will review and remove it promptly.
      </S>
      <S title="5. AI-generated content">
        Translations, summaries and audio narration are generated by AI and may contain errors.
        They are provided for convenience and are not substitutes for the original texts.
      </S>
      <S title="6. Availability & changes">
        Features may change, break or be withdrawn at any time. We may update these terms;
        continued use after changes constitutes acceptance.
      </S>
      <S title="7. Governing law">
        These terms are governed by the laws of India.
      </S>
    </>
  );
}

function Privacy() {
  return (
    <>
      <S title="What we collect">
        Your Google account basics on sign-in (name, email, profile photo); your public posts,
        follows and reading activity (book title and page, shown to other users); and reading
        preferences stored on your device.
      </S>
      <S title="What we do NOT collect">
        No advertising trackers, no location data, no contact lists, no selling of data — ever.
      </S>
      <S title="Where data lives">
        Account data and shared content are stored in Google Firebase (Firestore). Reading
        positions, bookmarks and preferences stay in your browser's local storage. Text sent
        for translation or narration is processed by Sarvam AI and Google Gemini APIs.
      </S>
      <S title="Your choices">
        You can sign out at any time. To delete your account data and posts, email {CONTACT}
        from your registered address and we will remove them within 30 days.
      </S>
      <S title="Children">
        Littgram is not directed at children under 13.
      </S>
    </>
  );
}

function Cookies() {
  return (
    <>
      <S title="What we use">
        Littgram does not set advertising or third-party analytics cookies. We use your
        browser's <b>local storage</b> for functional purposes only: keeping you signed in
        (Firebase Auth), remembering your reading position, bookmarks, language and display
        preferences, and remembering that you've seen the tutorial.
      </S>
      <S title="Third parties">
        Signing in with Google may set Google's own cookies, governed by Google's policies.
        Book cover images and fonts are loaded from third-party CDNs which may log requests.
      </S>
      <S title="Managing storage">
        You can clear Littgram's local storage from your browser settings at any time — you'll
        stay signed out and lose device-local preferences, not your account or posts.
      </S>
    </>
  );
}

function CookiePrefs() {
  const [functional] = useState(true);
  const [analytics, setAnalytics] = useState(localStorage.getItem('littgram_consent_analytics') === '1');
  function toggleAnalytics() {
    const v = !analytics;
    setAnalytics(v);
    if (v) localStorage.setItem('littgram_consent_analytics', '1');
    else localStorage.removeItem('littgram_consent_analytics');
  }
  const Row = ({ title, desc, on, onToggle, locked }) => (
    <div className="card" style={{ marginBottom: 10, display: 'flex', alignItems: 'center', gap: 12 }}>
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 13, fontWeight: 700 }}>{title}</div>
        <div className="sub" style={{ marginTop: 3 }}>{desc}</div>
      </div>
      <button onClick={locked ? undefined : onToggle} disabled={locked} style={{
        width: 44, height: 24, borderRadius: 12, border: 'none', cursor: locked ? 'not-allowed' : 'pointer',
        background: on ? 'var(--accent)' : 'var(--surface2)', position: 'relative', flexShrink: 0,
        opacity: locked ? 0.6 : 1,
      }}>
        <span style={{
          position: 'absolute', top: 3, left: on ? 23 : 3, width: 18, height: 18,
          borderRadius: '50%', background: on ? 'var(--accent-ink)' : 'var(--muted)', transition: 'left .2s',
        }} />
      </button>
    </div>
  );
  return (
    <>
      <Row title="Essential" locked on={functional}
        desc="Sign-in, reading positions, preferences. Required for the app to work." />
      <Row title="Analytics" on={analytics} onToggle={toggleAnalytics}
        desc="Currently unused — Littgram runs no analytics. This preference is honoured if analytics are ever added." />
    </>
  );
}

function Disclaimer() {
  return (
    <>
      <S title="AI-generated content">
        Translations, chapter summaries, five-minute audio summaries and narration on Littgram
        are produced by artificial intelligence. They may contain inaccuracies, omissions or
        artifacts, and do not represent the views of the original authors. Always refer to the
        original text for scholarly or critical use.
      </S>
      <S title="OCR fidelity">
        Digitized books are extracted from scans of printed editions. Despite quality checks,
        occasional recognition errors may remain.
      </S>
      <S title="No professional advice">
        Nothing on Littgram constitutes professional, legal, medical or financial advice.
      </S>
      <S title="Automated profiles">
        Profiles such as Motivations, Bharat Gyaan, Tagore Daily and Premchand Says are
        automated accounts that post excerpts from the catalog on a schedule. They are clearly
        machine-operated and not human users.
      </S>
    </>
  );
}

const PAGES = {
  about: { title: 'About Littgram', C: About },
  terms: { title: 'Terms of Use', C: Terms },
  privacy: { title: 'Privacy Policy', C: Privacy },
  cookies: { title: 'Cookie Policy', C: Cookies },
  'cookie-preferences': { title: 'Cookie Preferences', C: CookiePrefs },
  disclaimer: { title: 'Disclaimer', C: Disclaimer },
};

export default function Legal() {
  const { page } = useParams();
  const entry = PAGES[page] || PAGES.about;
  const C = entry.C;
  return (
    <div>
      <h1 className="h-screen serif">{entry.title}</h1>
      <p className="sub" style={{ marginBottom: 18 }}>Last updated {UPDATED} · Littgram, a personal project · India</p>
      <C />
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 22 }}>
        {Object.entries(PAGES).filter(([k]) => k !== (PAGES[page] ? page : 'about')).map(([k, v]) => (
          <Link key={k} className="pill sm" to={'/legal/' + k} style={{ textDecoration: 'none' }}>{v.title}</Link>
        ))}
      </div>
    </div>
  );
}
